// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | mono2
//    output | Desktop
//    input  | togepi_128x32.gif

#pragma once

#include <qp.h>

extern const uint32_t gfx_togepi_128x32_length;
extern const uint8_t  gfx_togepi_128x32[1390];
